### ISSUE TITLE
Material_SpecularGlossiness assets apply extensionsUsed but not extensionsRequired

### ISSUE THREAD

**Issue by najadojo** [KhronosGroup/glTF-Asset-Generator#434]
I suggest that the [SpecularGlossiness](https://github.com/bghgary/glTF-Asset-Generator/blob/master/Output/Material_SpecularGlossiness/README.md) test assets use 
```json
"extensionsRequired": [
    "KHR_materials_pbrSpecularGlossiness"
  ]
```
Because the assets don't render as expected on clients that do not support the extension.

**Comment by bghgary** [comment]
This is interesting. We put a red X so that it's obvious which one is being loaded, but typically with `extensionsUsed`, the asset should look as similar as possible. We already have a entry for `extensionsRequired` in the [Compatability](https://github.com/bghgary/glTF-Asset-Generator/tree/master/Output/Compatibility) page. Maybe we should add a `extensionsUsed` entry there as well.

**Comment by najadojo** [comment]
Our client tries to guess if there is a valid fallback so we don't have to convert the SpecularGlossiness to MetalRoughness. The red X makes our guess mostly wrong. Having extensionRequired would sway that guess.

**Comment by stevk** [comment]
@najadojo I've just added a change that should address the issue your client was having with the SpecularGlossiness models. Please check it out and let us know if there are further issues!
